version: '3.8'

services:
  bot:
    build: .
    container_name: blacklist-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - ./data:/app/data